import sharp from "sharp";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { randomUUID } from "node:crypto";
import { mkdir, writeFile, unlink } from "node:fs/promises";

export const serviceImagesDirectory = fileURLToPath(
  new URL("../uploads/services/", import.meta.url),
);

export async function saveServiceImage(file) {
  let buffer;

  try {
    const image = sharp(file.buffer, {
      limitInputPixels: 25_000_000,
    });

    const metadata = await image.metadata();

    if (
      !["jpeg", "png", "webp"].includes(metadata.format) ||
      (metadata.pages || 1) > 1
    ) {
      throw new Error("Unsupported image");
    }

    buffer = await image
      .rotate()
      .resize({
        width: 1400,
        height: 1400,
        fit: "inside",
        withoutEnlargement: true,
      })
      .webp({ quality: 85 })
      .toBuffer();
  } catch {
    const error = new Error(
      "Invalid image. Upload a valid, non-animated JPG, PNG or WebP.",
    );
    error.status = 400;
    throw error;
  }

  await mkdir(serviceImagesDirectory, { recursive: true });

  const filename = `${randomUUID()}.webp`;

  await writeFile(path.join(serviceImagesDirectory, filename), buffer, {
    flag: "wx",
  });

  return `/uploads/services/${filename}`;
}

export async function removeServiceImage(imageUrl) {
  // Only delete files generated by this uploader.
  // Existing seed images and external URLs are never deleted.
  const match = /^\/uploads\/services\/([a-f0-9-]{36}\.webp)$/.exec(
    imageUrl || "",
  );

  if (!match) return;

  try {
    await unlink(path.join(serviceImagesDirectory, match[1]));
  } catch (error) {
    if (error.code !== "ENOENT") {
      console.error("Could not remove unused service image:", error.message);
    }
  }
}
